---
spring:
  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

cpf-api-url: http://user-info.herokuapp.com/users/{cpf}
