---
spring:
  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html

cpf-api-url: http://user-info.herokuapp.com/users/{cpf}

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

---
spring:
  profiles: prod
  data:
    mongodb:
      uri: mongodb://heroku_8bd2pq45:91auipb2h3bn6mb2ger5jfr5sm@ds049170.mlab.com:49170/heroku_8bd2pq45?retryWrites=false

